#!/usr/bin/env python3
"""agent-resume: find and resume local CLI coding-agent sessions.

MVP supports:
- Codex CLI: codex exec resume <session|--last> "prompt"
- OpenCode: opencode --session <id> --prompt "prompt"
- Claude Code: claude --print --resume <session|--continue> "prompt"

The MCP server is NDJSON stdio for simple MCP relays.
"""
from __future__ import annotations

import argparse
import copy
import json
import os
import re
import shlex
import sqlite3
import subprocess
import sys
import time
import uuid
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

HOME = Path.home()
STATE_DIR = Path(os.environ.get("AGENT_RESUME_STATE_DIR", HOME / ".local/state/agent-resume"))
CONFIG_PATH = Path(os.environ.get("AGENT_RESUME_CONFIG", HOME / ".config/agent-resume/config.json"))
SERVER_NAME = "agent-resume"
SERVER_VERSION = "0.1.7"


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def normalize_agent(agent: str) -> str:
    a = (agent or "").strip().lower().replace("_", "-")
    aliases = {
        "codex-cli": "codex",
        "openai-codex": "codex",
        "opencode-ai": "opencode",
        "open-code": "opencode",
        "claude-code": "claude",
        "anthropic-claude": "claude",
    }
    a = aliases.get(a, a)
    if a not in {"codex", "opencode", "claude"}:
        raise ValueError("agent must be one of: codex, opencode, claude")
    return a


def load_config() -> Dict[str, Any]:
    if not CONFIG_PATH.exists():
        return {}
    try:
        return json.loads(CONFIG_PATH.read_text())
    except Exception:
        return {}


def default_agent() -> Optional[str]:
    for key in ("AGENT_RESUME_AGENT", "MCP_AGENT", "AI_AGENT", "AGENT"):
        val = os.environ.get(key)
        if val:
            return normalize_agent(val)
    cfg = load_config()
    val = cfg.get("agent") or cfg.get("default_agent")
    if val:
        return normalize_agent(str(val))
    return None


def resolve_agent(agent: Optional[str]) -> str:
    if agent:
        return normalize_agent(agent)
    resolved = default_agent()
    if resolved:
        return resolved
    raise ValueError(
        "agent is not configured. Set AGENT_RESUME_AGENT=codex|opencode|claude in this MCP server config, "
        "or pass agent explicitly, or write ~/.config/agent-resume/config.json with {\"agent\":\"codex\"}."
    )


MARKER_RE = re.compile(r"^[A-Za-z0-9]{5}$")


def now_ms() -> int:
    return int(datetime.now(timezone.utc).timestamp() * 1000)


def validate_marker(marker: Any, *, required: bool = False) -> Optional[str]:
    """Validate short correlation marker generated by the model.

    Exactly 5 ASCII alphanumeric chars. The MCP server records call time itself,
    so the model does not need to know the time or produce UUIDs.
    """
    if marker is None or str(marker).strip() == "":
        if required:
            raise ValueError("marker is required unless session_id is explicit. Pass exactly 5 ASCII alphanumeric chars, e.g. A7kQ2.")
        return None
    value = str(marker).strip()
    if not MARKER_RE.fullmatch(value):
        raise ValueError("marker must be exactly 5 ASCII alphanumeric chars [A-Za-z0-9]")
    return value


def get_marker(args: Dict[str, Any], *, required: bool = False) -> Optional[str]:
    # run_id is accepted as an old alias, but the expected name is marker.
    return validate_marker(args.get("marker") or args.get("run_id"), required=required)


def extract_mcp_session_id(meta: Any) -> Optional[str]:
    """Extract session/thread id passed by an MCP client in request _meta.

    Codex currently sends the conversation/thread id as _meta.threadId.
    Keep aliases for compatibility with other clients or future changes.
    """
    keys = {"threadId", "thread_id", "sessionId", "session_id", "conversationId", "conversation_id"}
    seen: set[int] = set()

    def walk(value: Any) -> Optional[str]:
        if isinstance(value, dict):
            oid = id(value)
            if oid in seen:
                return None
            seen.add(oid)
            for k in keys:
                v = value.get(k)
                if isinstance(v, str) and v.strip():
                    return v.strip()
            for v in value.values():
                found = walk(v)
                if found:
                    return found
        elif isinstance(value, list):
            for v in value:
                found = walk(v)
                if found:
                    return found
        return None

    return walk(meta)


def default_agent_or_none() -> Optional[str]:
    try:
        return resolve_agent(None)
    except Exception:
        return None


def text_has(needle: Optional[str], *values: Any) -> bool:
    if not needle:
        return False
    n = str(needle).lower()
    return n in "\n".join(str(v or "") for v in values).lower()


def match_score(query: Optional[str], marker: Optional[str], *values: Any) -> float:
    score = 0.0
    if marker and text_has(marker, *values):
        score += 100.0
    if query and text_has(query, *values):
        score += 10.0
    return score


def safe_cwd(cwd: Optional[str]) -> Path:
    p = Path(cwd or os.getcwd()).expanduser().resolve()
    if not p.exists() or not p.is_dir():
        raise FileNotFoundError(f"cwd not found or not a directory: {p}")
    return p


@dataclass
class SessionCandidate:
    agent: str
    session_id: str
    cwd: Optional[str] = None
    title: Optional[str] = None
    updated: Optional[float] = None
    source: Optional[str] = None
    score: float = 0.0
    extra: Optional[Dict[str, Any]] = None


def parse_time(value: Any) -> float:
    if value is None:
        return 0.0
    if isinstance(value, (int, float)):
        # Normalize epoch seconds / milliseconds / microseconds / nanoseconds.
        v = float(value)
        if v > 1_000_000_000_000_000_00:  # nanoseconds
            return v / 1_000_000_000.0
        if v > 1_000_000_000_000_00:  # microseconds
            return v / 1_000_000.0
        if v > 10_000_000_000:  # milliseconds
            return v / 1000.0
        return v
    text = str(value).strip()
    if not text:
        return 0.0
    if text.isdigit():
        return parse_time(int(text))
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    # Python 3.10 only accepts microseconds; Codex timestamps can have nanoseconds.
    if "." in text:
        head, tail = text.split(".", 1)
        tz = ""
        for sep in ("+", "-"):
            if sep in tail:
                frac, rest = tail.split(sep, 1)
                tz = sep + rest
                break
        else:
            frac = tail
        text = head + "." + frac[:6].ljust(6, "0") + tz
    try:
        return datetime.fromisoformat(text).timestamp()
    except Exception:
        return 0.0


def codex_sessions(cwd: Optional[Path] = None, limit: int = 20, query: Optional[str] = None, marker: Optional[str] = None) -> List[SessionCandidate]:
    """Find Codex sessions.

    Preferred source is ~/.codex/state_5.sqlite: threads table has id, cwd,
    title/preview, rollout_path, model, git metadata, updated_at_ms.
    Fallback is ~/.codex/session_index.jsonl, which has id/title/time but not cwd.
    """
    out: List[SessionCandidate] = []
    cwd_s = str(cwd) if cwd else None
    db = HOME / ".codex/state_5.sqlite"
    if db.exists():
        try:
            con = sqlite3.connect(f"file:{db}?mode=ro", uri=True, timeout=2)
            con.row_factory = sqlite3.Row
            rows = con.execute(
                "select id,cwd,title,preview,first_user_message,rollout_path,updated_at_ms,updated_at,created_at_ms,model,source,thread_source,agent_nickname,agent_role,git_origin_url,git_branch from threads where archived=0 order by updated_at_ms desc limit 500"
            ).fetchall()
            con.close()
            for r in rows:
                rcwd = r["cwd"] or None
                title = r["title"] or r["preview"] or r["first_user_message"] or ""
                score = 0.0
                if cwd_s and rcwd:
                    try:
                        d = str(Path(rcwd).expanduser().resolve())
                        if d == cwd_s:
                            score += 30
                        elif cwd_s.startswith(d.rstrip("/") + "/") or d.startswith(cwd_s.rstrip("/") + "/"):
                            score += 12
                    except Exception:
                        pass
                score += match_score(query, marker, title, rcwd, r["rollout_path"], r["git_branch"])
                if not r["agent_nickname"]:
                    score += 1
                out.append(SessionCandidate(
                    "codex", r["id"], rcwd, title[:300], parse_time(r["updated_at_ms"] or r["updated_at"]), str(db), score,
                    {"rollout_path": r["rollout_path"], "model": r["model"], "source": r["source"], "thread_source": r["thread_source"], "agent_nickname": r["agent_nickname"], "agent_role": r["agent_role"], "git_origin_url": r["git_origin_url"], "git_branch": r["git_branch"]}
                ))
        except Exception:
            pass
    if not out:
        path = HOME / ".codex/session_index.jsonl"
        if path.exists():
            for line in path.read_text(errors="replace").splitlines():
                try:
                    item = json.loads(line)
                except Exception:
                    continue
                sid = item.get("id")
                if not sid:
                    continue
                title = item.get("thread_name") or ""
                updated = item.get("updated_at")
                score = 0.0
                score += match_score(query, marker, title, str(cwd) if cwd else None)
                ts = parse_time(updated)
                out.append(SessionCandidate("codex", sid, str(cwd) if cwd else None, title, ts, str(path), score, {"updated_at": updated}))
    out.sort(key=lambda x: (x.score, x.updated or 0), reverse=True)
    return out[:limit]


def opencode_sessions(cwd: Optional[Path] = None, limit: int = 20, query: Optional[str] = None, marker: Optional[str] = None) -> List[SessionCandidate]:
    dbs = [
        HOME / ".local/share/opencode/opencode.db",
    ]
    # include per-branch/test DBs, newest first
    share = HOME / ".local/share/opencode"
    if share.exists():
        dbs.extend(sorted(share.glob("opencode-*.db"), key=lambda p: p.stat().st_mtime, reverse=True))
    out: List[SessionCandidate] = []
    cwd_s = str(cwd) if cwd else None
    for db in dbs:
        if not db.exists():
            continue
        try:
            con = sqlite3.connect(f"file:{db}?mode=ro", uri=True, timeout=2)
            con.row_factory = sqlite3.Row
            rows = con.execute(
                "select id,title,directory,path,agent,model,time_updated,time_created,parent_id from session where time_archived is null order by time_updated desc limit 200"
            ).fetchall()
        except Exception:
            continue
        finally:
            try:
                con.close()
            except Exception:
                pass
        for r in rows:
            directory = r["directory"] or None
            pathval = r["path"] or None
            title = r["title"] or ""
            score = 0.0
            if cwd_s and directory:
                try:
                    d = str(Path(directory).expanduser().resolve())
                    if d == cwd_s:
                        score += 20
                    elif cwd_s.startswith(d.rstrip("/") + "/") or d.startswith(cwd_s.rstrip("/") + "/"):
                        score += 8
                except Exception:
                    pass
            if cwd_s and pathval and pathval.strip("/") in cwd_s.strip("/"):
                score += 5
            score += match_score(query, marker, title, directory, pathval)
            # prefer root sessions by default
            if not r["parent_id"]:
                score += 1
            out.append(
                SessionCandidate(
                    "opencode",
                    r["id"],
                    directory,
                    title,
                    parse_time(r["time_updated"]),
                    str(db),
                    score,
                    {"path": pathval, "agent": r["agent"], "model": r["model"], "parent_id": r["parent_id"]},
                )
            )
    out.sort(key=lambda x: (x.score, x.updated or 0), reverse=True)
    return out[:limit]


def claude_project_dir(cwd: Path) -> Path:
    # Claude project dirs use path with slashes converted to hyphen, e.g. /home/x/foo -> -home-x-foo
    return HOME / ".claude/projects" / str(cwd).replace("/", "-")


def claude_sessions(cwd: Optional[Path] = None, limit: int = 20, query: Optional[str] = None, marker: Optional[str] = None) -> List[SessionCandidate]:
    roots: List[Path] = []
    if cwd:
        roots.append(claude_project_dir(cwd))
    all_root = HOME / ".claude/projects"
    if all_root.exists():
        roots.extend([p for p in all_root.iterdir() if p.is_dir() and p not in roots])
    out: List[SessionCandidate] = []
    for root in roots:
        for f in root.glob("*.jsonl"):
            sid = f.stem
            title = None
            try:
                # Read first/last few lines without loading huge files where possible.
                lines = f.read_text(errors="replace").splitlines()
                for line in lines[:20]:
                    try:
                        item = json.loads(line)
                    except Exception:
                        continue
                    msg = item.get("message") or {}
                    content = msg.get("content")
                    if isinstance(content, str) and content.strip():
                        title = content.strip().splitlines()[0][:120]
                        break
                    if isinstance(content, list):
                        for part in content:
                            if isinstance(part, dict) and part.get("type") == "text" and part.get("text"):
                                title = str(part["text"]).strip().splitlines()[0][:120]
                                break
                        if title:
                            break
            except Exception:
                pass
            score = 0.0
            if cwd and root == claude_project_dir(cwd):
                score += 20
            score += match_score(query, marker, title, path.name, str(f))
            out.append(SessionCandidate("claude", sid, str(cwd) if cwd else None, title, f.stat().st_mtime, str(f), score))
    out.sort(key=lambda x: (x.score, x.updated or 0), reverse=True)
    return out[:limit]


def find_sessions(agent: Optional[str] = None, cwd: Optional[str] = None, query: Optional[str] = None, limit: int = 20, marker: Optional[str] = None) -> List[Dict[str, Any]]:
    a = resolve_agent(agent)
    mk = validate_marker(marker) if marker else None
    p = safe_cwd(cwd) if cwd else None
    if a == "codex":
        rows = codex_sessions(p, limit, query, mk)
    elif a == "opencode":
        rows = opencode_sessions(p, limit, query, mk)
    else:
        rows = claude_sessions(p, limit, query, mk)
    return [asdict(x) for x in rows]


def default_prompt(job_id: Optional[str], log_file: Optional[str], status: Optional[Dict[str, Any]], note: Optional[str], marker: Optional[str] = None, called_at_ms: Optional[int] = None) -> str:
    rc = None
    state = None
    if status:
        rc = status.get("returncode")
        state = status.get("state")
    parts = ["Background job finished. Resume the previous task and continue from the result."]
    if marker:
        parts.append(f"Marker: {marker}")
    if called_at_ms:
        parts.append(f"MCP called_at_ms: {called_at_ms}")
    if note:
        parts.append(f"Note: {note}")
    if job_id:
        parts.append(f"Job id: {job_id}")
    if state:
        parts.append(f"State: {state}")
    if rc is not None:
        parts.append(f"Return code: {rc}")
    if log_file:
        parts.append(f"Log file: {log_file}")
        parts.append("Inspect the log/status as needed; do not repeat work already completed.")
    return "\n".join(parts)


def build_resume_command(agent: Optional[str], session_id: Optional[str], cwd: Optional[str], prompt: str, use_last: bool = False) -> List[str]:
    a = resolve_agent(agent)
    if a == "codex":
        if session_id:
            return ["codex", "exec", "resume", session_id, prompt]
        if use_last:
            raise ValueError("use_last is unsafe and disabled")
        raise ValueError("codex resume requires session_id")
    if a == "opencode":
        if session_id:
            return ["opencode", "--session", session_id, "--prompt", prompt]
        if use_last:
            raise ValueError("use_last is unsafe and disabled")
        raise ValueError("opencode resume requires session_id")
    if a == "claude":
        if session_id:
            return ["claude", "--print", "--resume", session_id, prompt]
        if use_last:
            raise ValueError("use_last is unsafe and disabled")
        raise ValueError("claude resume requires session_id")
    raise AssertionError(a)


def resume_agent(args: Dict[str, Any]) -> Dict[str, Any]:
    agent = resolve_agent(args.get("agent"))
    explicit_cwd = args.get("cwd")
    cwd = str(safe_cwd(explicit_cwd)) if explicit_cwd else str(Path.cwd())
    session_id = args.get("session_id") or args.get("session")
    mcp_meta = args.get("_mcp_meta") or args.get("_meta") or {}
    meta_session_id = extract_mcp_session_id(mcp_meta)

    if args.get("use_last"):
        raise ValueError("use_last is unsafe and disabled")

    if not session_id and agent == "codex" and meta_session_id:
        session_id = meta_session_id

    marker: Optional[str] = None
    candidates: List[Dict[str, Any]] = []

    if not session_id:
        if not explicit_cwd:
            raise ValueError(f"cwd is required for {agent} when session_id was not provided by MCP _meta")
        marker = get_marker(args, required=True)
        query = args.get("query") or args.get("title_query")
        candidates = find_sessions(agent, cwd, query=query, limit=5, marker=marker)
        if candidates and float(candidates[0].get("score") or 0) >= 100.0:
            session_id = candidates[0]["session_id"]
        if not session_id:
            raise ValueError(f"no session matched marker={marker!r} cwd={cwd!r}; refusing to resume")
    else:
        # Marker can still be supplied for logs/prompt, but Codex does not need it
        # because its session id comes through MCP _meta.threadId.
        marker = validate_marker(args.get("marker"), required=False) if args.get("marker") else None

    called_at_ms = now_ms()
    prompt = args.get("prompt") or default_prompt(args.get("job_id"), args.get("log_file"), args.get("status"), args.get("note"), marker=marker, called_at_ms=called_at_ms)
    cmd = build_resume_command(agent, str(session_id), cwd, str(prompt), use_last=False)
    result: Dict[str, Any] = {
        "ok": True,
        "agent": agent,
        "cwd": cwd,
        "session_id": session_id,
        "session_id_source": "mcp_meta" if meta_session_id and meta_session_id == session_id else ("argument" if args.get("session_id") or args.get("session") else "marker_lookup"),
        "marker": marker,
        "called_at_ms": called_at_ms,
        "used_last": False,
        "candidates": candidates,
        "command": cmd,
        "shell_command": " ".join(shlex.quote(x) for x in cmd),
        "executed": False,
    }
    if args.get("execute"):
        log_dir = STATE_DIR / "runs"
        log_dir.mkdir(parents=True, exist_ok=True)
        launch_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + f"-{agent}"
        log = log_dir / f"{launch_id}.log"
        shell = f"setsid {' '.join(shlex.quote(x) for x in cmd)} > {shlex.quote(str(log))} 2>&1 < /dev/null & echo $!"
        p = subprocess.run(["/bin/bash", "-lc", shell], cwd=cwd, text=True, capture_output=True, timeout=10)
        result.update({"executed": True, "launch_returncode": p.returncode, "launch_stdout": p.stdout, "launch_stderr": p.stderr, "log_file": str(log)})
        try:
            result["pid"] = int(p.stdout.strip().splitlines()[-1])
        except Exception:
            result["pid"] = None
        result["ok"] = p.returncode == 0
    return result


# ---------------- background wait/resume ----------------

def parse_duration_seconds(value: Any, default: int = 0) -> int:
    if value is None or value == "":
        return default
    if isinstance(value, (int, float)):
        return max(0, int(float(value)))
    text = str(value).strip().lower()
    if not text:
        return default
    for suffix, mult in (("ms", 0.001), ("s", 1), ("m", 60), ("h", 3600)):
        if text.endswith(suffix):
            try:
                return max(0, int(float(text[:-len(suffix)].strip()) * mult + 0.999))
            except Exception as e:
                raise ValueError(f"invalid duration: {value!r}") from e
    try:
        return max(0, int(float(text)))
    except Exception as e:
        raise ValueError(f"invalid duration: {value!r}") from e


def is_pid_alive(pid: int) -> bool:
    try:
        stat = Path(f"/proc/{pid}/stat")
        if stat.exists():
            parts = stat.read_text(errors="replace").split()
            if len(parts) >= 3 and parts[2] == "Z":
                return False
        os.kill(pid, 0)
        return True
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    except Exception:
        return False


def find_pids_by_query(query: str) -> List[Dict[str, Any]]:
    q = str(query or "").strip()
    if not q:
        raise ValueError("query is required")
    me = os.getpid()
    p = subprocess.run(["/bin/bash", "-lc", "ps -eo pid=,args="], text=True, capture_output=True, timeout=10)
    matches: List[Dict[str, Any]] = []
    for line in p.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            pid_s, cmd = line.split(None, 1)
            pid = int(pid_s)
        except Exception:
            continue
        if pid == me:
            continue
        if q in cmd and "agent_resume.py" not in cmd:
            matches.append({"pid": pid, "cmd": cmd[:500]})
    return matches


def agent_resume_script() -> str:
    return str(Path(__file__).resolve())


def job_paths(job_id: Optional[str] = None) -> Dict[str, Path]:
    jid = job_id or (datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + "-" + uuid.uuid4().hex[:8])
    root = STATE_DIR / "jobs" / jid
    return {"job_id": Path(jid), "root": root, "meta": root / "meta.json", "log": root / "job.log", "watcher_log": root / "watcher.log"}


def write_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True))
    os.replace(tmp, path)


def read_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text())


def freeze_resume_target(args: Dict[str, Any]) -> Dict[str, Any]:
    frozen_args = dict(args)
    frozen_args.pop("execute", None)
    # Build once while MCP _meta is available; this freezes Codex thread id now.
    frozen = resume_agent(frozen_args)
    return {
        "agent": frozen["agent"],
        "cwd": frozen["cwd"],
        "session_id": frozen["session_id"],
        "session_id_source": frozen.get("session_id_source"),
        "marker": frozen.get("marker"),
    }


def start_watcher(meta_path: Path) -> Dict[str, Any]:
    watcher_log = meta_path.parent / "watcher.log"
    cmd = f"setsid {shlex.quote(sys.executable)} {shlex.quote(agent_resume_script())} _watch --meta {shlex.quote(str(meta_path))} > {shlex.quote(str(watcher_log))} 2>&1 < /dev/null & echo $!"
    p = subprocess.run(["/bin/bash", "-lc", cmd], text=True, capture_output=True, timeout=10)
    if p.returncode != 0:
        raise RuntimeError(f"failed to start watcher: {p.stderr or p.stdout}")
    return {"watcher_pid": int(p.stdout.strip().splitlines()[-1]), "watcher_log": str(watcher_log)}


def tool_run_and_resume(args: Dict[str, Any]) -> Dict[str, Any]:
    command = str(args.get("command") or "").strip()
    if not command:
        raise ValueError("command is required")
    cwd = str(safe_cwd(args.get("cwd")))
    target = freeze_resume_target(args)
    paths = job_paths(str(args.get("job_id") or "").strip() or None)
    root = paths["root"]; root.mkdir(parents=True, exist_ok=False)
    log_file = str(args.get("log_file") or paths["log"])
    hard_timeout = parse_duration_seconds(args.get("hard_timeout", "0"), default=0)
    note = str(args.get("note") or "")
    launch = subprocess.run(
        ["/bin/bash", "-lc", f"setsid bash -lc {shlex.quote(command)} > {shlex.quote(log_file)} 2>&1 < /dev/null & echo $!"],
        cwd=cwd, text=True, capture_output=True, timeout=10,
    )
    if launch.returncode != 0:
        raise RuntimeError(f"failed to launch command: {launch.stderr or launch.stdout}")
    pid = int(launch.stdout.strip().splitlines()[-1])
    meta = {
        "job_id": paths["job_id"].name,
        "kind": "command",
        "state": "running",
        "created_at": now_iso(),
        "started_at": now_iso(),
        "command": command,
        "pid": pid,
        "cwd": cwd,
        "log_file": log_file,
        "hard_timeout_seconds": hard_timeout,
        "note": note,
        "resume": target,
        "execute_resume": bool(args.get("execute_resume", True)),
    }
    write_json(paths["meta"], meta)
    meta.update(start_watcher(paths["meta"]))
    write_json(paths["meta"], meta)
    return {"ok": True, "job_id": meta["job_id"], "pid": pid, "log_file": log_file, "watcher_pid": meta["watcher_pid"], "watcher_log": meta["watcher_log"], "resume": target}


def tool_attach_pid_and_resume(args: Dict[str, Any]) -> Dict[str, Any]:
    pid = int(args.get("pid") or 0)
    if pid <= 0:
        raise ValueError("pid must be positive")
    if not is_pid_alive(pid):
        raise ValueError(f"pid {pid} is not alive")
    target = freeze_resume_target(args)
    paths = job_paths(str(args.get("job_id") or "").strip() or None)
    root = paths["root"]; root.mkdir(parents=True, exist_ok=False)
    log_file = str(args.get("log_file") or "") or None
    meta = {
        "job_id": paths["job_id"].name,
        "kind": "pid",
        "state": "running",
        "created_at": now_iso(),
        "pid": pid,
        "cwd": str(safe_cwd(args.get("cwd"))),
        "log_file": log_file,
        "hard_timeout_seconds": parse_duration_seconds(args.get("hard_timeout", "0"), default=0),
        "note": str(args.get("note") or ""),
        "resume": target,
        "execute_resume": bool(args.get("execute_resume", True)),
    }
    write_json(paths["meta"], meta)
    meta.update(start_watcher(paths["meta"]))
    write_json(paths["meta"], meta)
    return {"ok": True, "job_id": meta["job_id"], "pid": pid, "log_file": log_file, "watcher_pid": meta["watcher_pid"], "watcher_log": meta["watcher_log"], "resume": target}


def tool_attach_query_and_resume(args: Dict[str, Any]) -> Dict[str, Any]:
    matches = find_pids_by_query(str(args.get("query") or ""))
    if not matches:
        raise ValueError("no process matched query")
    if len(matches) > 1 and not bool(args.get("first", False)):
        raise ValueError(f"query matched multiple processes; pass first=true or pid. matches={matches[:5]}")
    pid = int(matches[0]["pid"])
    next_args = dict(args)
    next_args["pid"] = pid
    result = tool_attach_pid_and_resume(next_args)
    result["matched"] = matches[0]
    return result


def tool_wait_and_resume(args: Dict[str, Any]) -> Dict[str, Any]:
    wait_seconds = parse_duration_seconds(args.get("wait_seconds", args.get("seconds")), default=0)
    if wait_seconds <= 0:
        raise ValueError("wait_seconds must be > 0")
    target = freeze_resume_target(args)
    paths = job_paths(str(args.get("job_id") or "").strip() or None)
    root = paths["root"]; root.mkdir(parents=True, exist_ok=False)
    meta = {
        "job_id": paths["job_id"].name,
        "kind": "timer",
        "state": "running",
        "created_at": now_iso(),
        "wait_seconds": wait_seconds,
        "cwd": str(safe_cwd(args.get("cwd"))),
        "log_file": str(args.get("log_file") or "") or None,
        "note": str(args.get("note") or ""),
        "resume": target,
        "execute_resume": bool(args.get("execute_resume", True)),
    }
    write_json(paths["meta"], meta)
    meta.update(start_watcher(paths["meta"]))
    write_json(paths["meta"], meta)
    return {"ok": True, "job_id": meta["job_id"], "wait_seconds": wait_seconds, "watcher_pid": meta["watcher_pid"], "watcher_log": meta["watcher_log"], "resume": target}


def tool_wait_job_status(args: Dict[str, Any]) -> Dict[str, Any]:
    job_id = str(args.get("job_id") or "").strip()
    if not job_id:
        raise ValueError("job_id is required")
    meta = STATE_DIR / "jobs" / job_id / "meta.json"
    if not meta.exists():
        raise FileNotFoundError(f"job not found: {job_id}")
    data = read_json(meta)
    pid = data.get("pid")
    data["alive"] = bool(pid and is_pid_alive(int(pid)))
    return data


def watcher_main(meta_path: str) -> int:
    path = Path(meta_path)
    meta = read_json(path)
    start = time.time()
    timeout_s = int(meta.get("hard_timeout_seconds") or 0)
    state = "finished"
    timed_out = False
    pid = meta.get("pid")
    try:
        if meta.get("kind") == "timer":
            time.sleep(int(meta.get("wait_seconds") or 0))
        elif pid:
            while is_pid_alive(int(pid)):
                if timeout_s and time.time() - start >= timeout_s:
                    timed_out = True
                    state = "timeout"
                    break
                time.sleep(2)
        meta["finished_at"] = now_iso()
        meta["elapsed_seconds"] = int(time.time() - start)
        meta["state"] = state
        meta["timed_out"] = timed_out
        note_parts = []
        if meta.get("note"):
            note_parts.append(str(meta["note"]))
        if meta.get("kind") == "timer":
            note_parts.append(f"Timer elapsed after {meta.get('wait_seconds')}s.")
        elif timed_out:
            note_parts.append(f"Hard timeout reached after {timeout_s}s; watched process may still be alive.")
        else:
            note_parts.append("Watched process finished.")
        resume = dict(meta.get("resume") or {})
        resume_args = {
            "agent": resume.get("agent"),
            "cwd": resume.get("cwd") or meta.get("cwd"),
            "session_id": resume.get("session_id"),
            "job_id": meta.get("job_id"),
            "log_file": meta.get("log_file"),
            "note": " ".join(note_parts),
            "execute": bool(meta.get("execute_resume", True)),
        }
        result = resume_agent(resume_args)
        meta["resume_result"] = result
        write_json(path, meta)
        return 0 if result.get("ok") else 1
    except Exception as e:
        meta["state"] = "watcher_error"
        meta["error"] = f"{e.__class__.__name__}: {e}"
        meta["finished_at"] = now_iso()
        write_json(path, meta)
        print(meta["error"], file=sys.stderr)
        return 1


def register(args: Dict[str, Any]) -> Dict[str, Any]:
    agent = resolve_agent(args.get("agent"))
    cwd = str(safe_cwd(args.get("cwd")))
    session_id = args.get("session_id") or args.get("session")
    label = args.get("label") or args.get("name") or "default"
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    marker = validate_marker(args.get("marker")) if args.get("marker") else None
    rec = {"agent": agent, "cwd": cwd, "session_id": session_id, "marker": marker, "label": label, "updated_at": now_iso(), "metadata": args.get("metadata") or {}}
    path = STATE_DIR / "registry.jsonl"
    with path.open("a") as f:
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    return {"ok": True, "record": rec, "registry": str(path)}


BASE_TOOLS = {
    "get_config": {
        "description": "Show agent-resume effective config: default agent from env/config and state paths. Use this to verify the MCP server identity; normal calls do not need an agent argument when AGENT_RESUME_AGENT is set.",
        "inputSchema": {"type":"object","properties":{},"additionalProperties":False},
        "handler": lambda a: {"default_agent": default_agent(), "config_path": str(CONFIG_PATH), "config": load_config(), "env_agent": os.environ.get("AGENT_RESUME_AGENT"), "state_dir": str(STATE_DIR)},
    },
    "find_sessions": {
        "description": "Find likely local CLI coding-agent sessions. Agent is optional when AGENT_RESUME_AGENT=codex|opencode|claude is set in this MCP server config. Use cwd/query/marker to pick the right chat before resuming.",
        "inputSchema": {"type":"object","properties":{"agent":{"type":"string","enum":["codex","opencode","claude"]},"cwd":{"type":["string","null"],"description":"Project directory to scope session search."},"query":{"type":["string","null"],"description":"Optional title/text query."},"marker":{"type":["string","null"],"description":"Short correlation marker: exactly 5 ASCII alphanumeric chars. Adds exact-match scoring; MCP records call time itself."},"limit":{"type":["integer","null"],"default":20}},"required":[],"additionalProperties":False},
        "handler": lambda a: {"sessions": find_sessions(a.get("agent"), a.get("cwd"), a.get("query"), int(a.get("limit") or 20), a.get("marker"))},
    },
    "build_resume_command": {
        "description": "Build the command that would resume an agent session. Schema is specialized by AGENT_RESUME_AGENT: Codex uses MCP _meta.threadId/session_id; OpenCode and Claude require cwd + marker. use_last is disabled.",
        "inputSchema": {"type":"object","properties":{"agent":{"type":"string","enum":["codex","opencode","claude"]},"cwd":{"type":["string","null"]},"session_id":{"type":["string","null"]},"prompt":{"type":["string","null"]},"job_id":{"type":["string","null"]},"log_file":{"type":["string","null"]},"note":{"type":["string","null"]},"query":{"type":["string","null"]},"marker":{"type":["string","null"],"description":"Required unless session_id is explicit. Exactly 5 ASCII alphanumeric chars [A-Za-z0-9]."},"execute":{"type":"boolean","default":False,"description":"If true, start the resume command detached. Default false for safety."}},"required":[],"additionalProperties":True},
        "handler": resume_agent,
    },
    "run_and_resume": {
        "description": "Run a non-interactive command in background, wait until it finishes or hard_timeout is reached, then resume the same agent chat. This is the agent-resume replacement for notify long-wait flow. For Codex the current thread is frozen from MCP _meta; for OpenCode/Claude pass cwd+marker.",
        "inputSchema": {"type":"object","properties":{"agent":{"type":"string","enum":["codex","opencode","claude"]},"command":{"type":"string"},"cwd":{"type":["string","null"]},"marker":{"type":["string","null"],"description":"Required for OpenCode/Claude unless session_id is explicit."},"session_id":{"type":["string","null"]},"query":{"type":["string","null"]},"job_id":{"type":["string","null"]},"log_file":{"type":["string","null"]},"note":{"type":["string","null"]},"hard_timeout":{"type":["string","integer","null"],"default":"0","description":"Maximum watch time, e.g. 30m, 1h. 0 disables timeout. Does not kill the process; resumes with timeout note."},"execute_resume":{"type":"boolean","default":True,"description":"Default true. Set false only for tests: watcher records the resume command but does not launch it."}},"required":["command"],"additionalProperties":True},
        "handler": tool_run_and_resume,
    },
    "attach_pid_and_resume": {
        "description": "Watch an existing PID and resume the same agent chat when it exits or hard_timeout is reached. For Codex current thread comes from MCP _meta; for OpenCode/Claude pass cwd+marker.",
        "inputSchema": {"type":"object","properties":{"agent":{"type":"string","enum":["codex","opencode","claude"]},"pid":{"type":"integer"},"cwd":{"type":["string","null"]},"marker":{"type":["string","null"]},"session_id":{"type":["string","null"]},"job_id":{"type":["string","null"]},"log_file":{"type":["string","null"]},"note":{"type":["string","null"]},"hard_timeout":{"type":["string","integer","null"],"default":"0"},"execute_resume":{"type":"boolean","default":True,"description":"Default true. Set false only for tests."}},"required":["pid"],"additionalProperties":True},
        "handler": tool_attach_pid_and_resume,
    },
    "attach_query_and_resume": {
        "description": "Find a process by command substring, watch it, and resume the same agent chat when it exits or hard_timeout is reached. Safer to pass pid when known; pass first=true only if multiple matches are acceptable.",
        "inputSchema": {"type":"object","properties":{"agent":{"type":"string","enum":["codex","opencode","claude"]},"query":{"type":"string"},"first":{"type":"boolean","default":False},"cwd":{"type":["string","null"]},"marker":{"type":["string","null"]},"session_id":{"type":["string","null"]},"job_id":{"type":["string","null"]},"log_file":{"type":["string","null"]},"note":{"type":["string","null"]},"hard_timeout":{"type":["string","integer","null"],"default":"0"},"execute_resume":{"type":"boolean","default":True,"description":"Default true. Set false only for tests."}},"required":["query"],"additionalProperties":True},
        "handler": tool_attach_query_and_resume,
    },
    "wait_and_resume": {
        "description": "Wait a fixed duration, then resume the same agent chat. Useful when the thing to wait for has no stable PID but a timed follow-up is needed. For long command/process waits prefer run_and_resume or attach_pid_and_resume.",
        "inputSchema": {"type":"object","properties":{"agent":{"type":"string","enum":["codex","opencode","claude"]},"wait_seconds":{"type":["string","integer"]},"cwd":{"type":["string","null"]},"marker":{"type":["string","null"]},"session_id":{"type":["string","null"]},"job_id":{"type":["string","null"]},"log_file":{"type":["string","null"]},"note":{"type":["string","null"]},"execute_resume":{"type":"boolean","default":True,"description":"Default true. Set false only for tests."}},"required":["wait_seconds"],"additionalProperties":True},
        "handler": tool_wait_and_resume,
    },
    "wait_job_status": {
        "description": "Read status for an agent-resume background wait job created by run_and_resume/attach_*_and_resume/wait_and_resume.",
        "inputSchema": {"type":"object","properties":{"job_id":{"type":"string"}},"required":["job_id"],"additionalProperties":False},
        "handler": tool_wait_job_status,
    },
    "register_agent": {
        "description": "Optional manual registration of current client/session. Normally agent identity should be configured once through AGENT_RESUME_AGENT in the MCP config, not passed on every call.",
        "inputSchema": {"type":"object","properties":{"agent":{"type":"string","enum":["codex","opencode","claude"]},"cwd":{"type":["string","null"]},"session_id":{"type":["string","null"]},"label":{"type":["string","null"]},"marker":{"type":["string","null"],"description":"Exactly 5 ASCII alphanumeric chars [A-Za-z0-9] correlation marker."},"metadata":{"type":["object","null"]}},"required":[],"additionalProperties":True},
        "handler": register,
    },
}


def tools_for_client() -> Dict[str, Dict[str, Any]]:
    tools = copy.deepcopy(BASE_TOOLS)
    agent = default_agent_or_none()
    schema = tools["build_resume_command"]["inputSchema"]
    props = schema["properties"]

    wait_tools = ["run_and_resume", "attach_pid_and_resume", "attach_query_and_resume", "wait_and_resume"]

    def tune_wait_tools(required_extra: List[str], marker_text: str) -> None:
        for name in wait_tools:
            ws = tools[name]["inputSchema"]
            base = list(ws.get("required") or [])
            for item in required_extra:
                if item not in base:
                    base.append(item)
            ws["required"] = base
            if "marker" in ws.get("properties", {}):
                ws["properties"]["marker"]["description"] = marker_text

    if agent == "codex":
        schema["required"] = []
        props["marker"]["description"] = "Optional for Codex: Codex passes session id as MCP _meta.threadId. Use marker only as fallback/debug."
        schema["description"] = "Codex: session id is taken from MCP request _meta.threadId; marker is not required. use_last is disabled."
        tools["build_resume_command"]["description"] = schema["description"]
        tune_wait_tools([], "Optional for Codex; current thread id is captured from MCP _meta before the watcher starts.")
    elif agent in {"opencode", "claude"}:
        schema["required"] = ["cwd", "marker"]
        props["cwd"]["description"] = "Required for OpenCode/Claude session lookup."
        props["marker"]["description"] = "Required for OpenCode/Claude. Exactly 5 ASCII alphanumeric chars [A-Za-z0-9]."
        schema["description"] = f"{agent}: cwd and marker are required; session id is not provided by MCP. use_last is disabled."
        tools["build_resume_command"]["description"] = schema["description"]
        tune_wait_tools(["cwd", "marker"], f"Required for {agent}; exactly 5 ASCII alphanumeric chars [A-Za-z0-9].")
    else:
        schema["anyOf"] = [{"required": ["session_id"]}, {"required": ["cwd", "marker"]}]
        props["marker"]["description"] = "Required with cwd unless session_id is explicit. Exactly 5 ASCII alphanumeric chars [A-Za-z0-9]."
        schema["description"] = "Generic mode: provide explicit session_id or cwd + marker. Codex client configs normally pass session id via _meta.threadId."
        tools["build_resume_command"]["description"] = schema["description"]
        for name in wait_tools:
            tools[name]["inputSchema"]["anyOf"] = [{"required": ["session_id"]}, {"required": ["cwd", "marker"]}]
    return tools


def reply(req_id: Any, result: Any = None, error: Exception | None = None) -> None:
    if req_id is None:
        return
    if error:
        payload = {"jsonrpc":"2.0","id":req_id,"error":{"code":-32000,"message":str(error),"data":error.__class__.__name__}}
    else:
        payload = {"jsonrpc":"2.0","id":req_id,"result":result}
    print(json.dumps(payload, ensure_ascii=False), flush=True)


def handle(req: Dict[str, Any]) -> None:
    method = req.get("method")
    req_id = req.get("id")
    try:
        if method == "initialize":
            reply(req_id, {"protocolVersion":"2024-11-05","capabilities":{"tools":{}},"serverInfo":{"name":SERVER_NAME,"version":SERVER_VERSION}})
        elif method == "tools/list":
            tools = tools_for_client(); reply(req_id, {"tools":[{"name":n,"description":t["description"],"inputSchema":t["inputSchema"]} for n,t in tools.items()]})
        elif method == "tools/call":
            params=req.get("params") or {}; name=params.get("name"); args=dict(params.get("arguments") or {})
            tools = tools_for_client()
            if name not in tools: raise ValueError(f"unknown tool: {name}")
            if isinstance(params.get("_meta"), dict): args["_mcp_meta"] = params.get("_meta")
            elif isinstance(params.get("meta"), dict): args["_mcp_meta"] = params.get("meta")
            result=tools[name]["handler"](args)
            reply(req_id, {"content":[{"type":"text","text":json.dumps(result, ensure_ascii=False, indent=2)}],"structuredContent":result})
        elif method and method.startswith("notifications/"):
            return
        else:
            reply(req_id, {})
    except Exception as e:
        print(f"agent-resume error: {e}", file=sys.stderr, flush=True)
        reply(req_id, error=e)


def mcp_main() -> None:
    for line in sys.stdin:
        line=line.strip()
        if not line: continue
        try: handle(json.loads(line))
        except Exception as e: print(f"bad request: {e}", file=sys.stderr, flush=True)


def cli_main() -> None:
    ap=argparse.ArgumentParser(description="Find and resume local CLI coding-agent sessions")
    sub=ap.add_subparsers(dest="cmd", required=True)
    f=sub.add_parser("find")
    f.add_argument("--agent", choices=["codex","opencode","claude"], help="Defaults to AGENT_RESUME_AGENT/config.json"); f.add_argument("--cwd"); f.add_argument("--query"); f.add_argument("--marker"); f.add_argument("--limit", type=int, default=20)
    r=sub.add_parser("resume")
    r.add_argument("--agent", choices=["codex","opencode","claude"], help="Defaults to AGENT_RESUME_AGENT/config.json"); r.add_argument("--cwd"); r.add_argument("--session-id"); r.add_argument("--prompt"); r.add_argument("--job-id"); r.add_argument("--log-file"); r.add_argument("--note"); r.add_argument("--query"); r.add_argument("--marker"); r.add_argument("--execute", action="store_true")
    w = sub.add_parser("_watch"); w.add_argument("--meta", required=True)
    sub.add_parser("mcp")
    args=ap.parse_args()
    if args.cmd == "_watch": raise SystemExit(watcher_main(args.meta))
    if args.cmd == "mcp": mcp_main(); return
    if args.cmd == "find": print(json.dumps({"sessions": find_sessions(args.agent, args.cwd, args.query, args.limit, args.marker)}, ensure_ascii=False, indent=2)); return
    if args.cmd == "resume": print(json.dumps(resume_agent(vars(args)), ensure_ascii=False, indent=2)); return

if __name__ == "__main__":
    cli_main()
